language: node_js
node_js:
  - "stable"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coverage # Include coverage when running tests
after_script: # Upload coverage reports 
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r 9ae9a121b196e43c267c8f9e05e404aedd52ab89cf5d314d19f6980d07d799c9