export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT__USER = 'LOG_OUT'
// export const RESET_PASSWORD = 'RESET_PASSWORD';


export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';
export const USER_BUSINESSES = 'USER_BUSINESSES';
export const SINGLE_BUSINESS = 'SINGLE_BUSINESS';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';
export const EDIT_BUSINESS = 'EDIT_BUSINESS';