export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
// export const RESET_PASSWORD = 'RESET_PASSWORD';


export const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';